
---
- set_fact:
    fuse_online_template: https://raw.githubusercontent.com/syndesisio/fuse-online-install/{{ fuse_online_release_tag }}/resources/fuse-online-template.yml

# Used to pull images from registry.redhat.io
- include_role:
    name: fuse_pull_secret
  vars:
    namespace: "{{ fuse_namespace }}"

- include_role:
    name: fuse
    tasks_from: _upgrade_fuse_online_imagestreams
  vars:
    fuse_upgrade_image_tag: "{{ fuse_image_tag }}"

- name: Update fuse operator resources in {{ fuse_namespace }}
  shell: oc replace --force -f {{ fuse_online_operator_resources }} -n {{ fuse_namespace }}

# Upgrade syndesis resources. This should bypass the upgrade phase of the operator
- name: Update and create new resources added to the fuse online template
  block:
    - name: Get syndesis global config secret params
      shell: oc get secret syndesis-global-config -o template --template \{\{.data.params\}\} -n {{ fuse_namespace }} | base64 --decode > /tmp/syndesis-params.yaml
    - name: Format syndesis parameter file
      shell: "sed -i 's/^/-p /' /tmp/syndesis-params.yaml"
    - shell: sed -i -z "s/\\n/ /g" /tmp/syndesis-params.yaml
    - name: Get syndesis parameters
      shell: "cat /tmp/syndesis-params.yaml"
      register: syndesis_parameters
    - name: Create new resources added to the fuse online template
      shell: "oc process -n {{ fuse_namespace }} -f {{ fuse_online_template }} -p SAR_PROJECT={{ fuse_namespace }} -p MAX_INTEGRATIONS_PER_USER=0 {{ syndesis_parameters.stdout }} | oc apply -n {{ fuse_namespace }} -f -"
      register: update_fuse_online_template_resources
      failed_when: update_fuse_online_template_resources.stderr != '' and 'Warning' not in update_fuse_online_template_resources.stderr and 'metadata.resourceVersion' not in update_fuse_online_template_resources.stderr

# Update Syndesis CR to 1.3
- name: Update version of Fuse custom resource to 1.3
  shell: "oc patch syndesis/fuse-managed --type=json --patch='[{\"op\": \"replace\", \"path\": \"/status/version\", \"value\": \"1.3\"}]' -n {{ fuse_namespace }}"

- name: Verify Fuse upgrade succeeded
  shell: oc get pods -n {{ fuse_namespace }} --selector="app=syndesis" -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}' | wc -w
  register: fuse_verify_result
  until: fuse_verify_result.stdout.find("8") != -1
  retries: 50
  delay: 10
  changed_when: False
