---
# ADDS CRUD SPRING BOOT EXAMPLE APP TO THE CATALOG
- name: template Node.js Orders Management UI
  template:
    src: nodejs_orders_management_ui.yml
    dest: /tmp/nodejs_orders_management_ui.yml
  
- name: Add crud spring boot example app to the catalog
  command: oc create -f /tmp/nodejs_orders_management_ui.yml -n openshift
  register: out
  until: '"created" in out.stdout or "AlreadyExists" in out.stderr'
  retries: 200
  delay: 5
  failed_when: out.stderr != '' and 'AlreadyExists' not in out.stderr