---
- name: Add walkthrough apps to the catalog
  include_tasks: '{{ item  }}.yml'
  with_items:
    - "messaging_work_queue_nodejs"
    - "camel_orders_api"
    - "nodejs_orders_management_ui"
    - "location_soap"