---

- set_fact:
    wt_route_name: "wt-{{ username }}"

- name: Check user walkthroughs route exists
  shell: oc get route/{{ wt_route_name }} -n {{ threescale_namespace }}
  register: wt_route_cmd
  failed_when: false

- name: Create user walkthroughs route
  shell:
    cmd: |
      cat <<EOF | oc apply -n {{ threescale_namespace }} -f -
        apiVersion: v1
        kind: Route
        metadata:
            labels:
              app: 3scale
            name: "{{ wt_route_name }}"
        spec:
            host: "{{ wt_route_name }}-{{ threescale_namespace }}.{{ threescale_route_suffix }}"
            port:
              targetPort: gateway
            tls:
              insecureEdgeTerminationPolicy: None
              termination: edge
            to:
              kind: Service
              name: apicast-staging
      EOF
  when: wt_route_cmd.stderr != '' and 'NotFound' in wt_route_cmd.stderr
