---
- hosts: local
  tasks:
    - block:
        - debug:
            msg: "eval_app_host is required when run_master_tasks=false"
          failed_when: eval_app_host is not defined
        - debug:
            msg: "openshift_master_url is required when run_master_tasks=false"
          failed_when: openshift_master_url is not defined
        - name: Set EVAL_VARS from vars as not running master tasks
          add_host:
            name: EVAL_VARS
            eval_app_host: "{{ eval_app_host }}"
            openshift_master_url: "{{ openshift_master_url }}"
        - name: Overwrite create_cluster_admin, set to false
          set_fact:
            create_cluster_admin: false
      when: not (run_master_tasks | default(true) | bool)

- hosts: master
  gather_facts: no
  tasks:
    - block:
        -
          name: Retrieve master configurations
          slurp:
            src: "{{ eval_openshift_master_config_path }}"
          register: eval_master_config
          become: yes
        -
          add_host:
            name: EVAL_VARS
            eval_app_host: "{{ (eval_master_config['content'] | b64decode | from_yaml)['routingConfig']['subdomain'] }}"
            openshift_master_url: "{{ (eval_master_config['content'] | b64decode | from_yaml)['masterPublicURL'] }}"
      tags: ['bootstrap', 'remote']
      when: run_master_tasks | default(true) | bool

- hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: prerequisites
        tasks_from: upgrade
      vars:
        from_version: "release-1.3.0"

    - include_role:
        name: rhsso
        tasks_from: upgrade
      vars:
        upgrade_sso_operator_image: quay.io/integreatly/keycloak-operator:{{ rhsso_operator_release_tag }}

    - include_role:
        name: msbroker
        tasks_from: upgrade
      vars:
        upgrade_msb_image: quay.io/integreatly/managed-service-broker:{{ msbroker_release_tag }}

    - include_role:
        name: webapp
        tasks_from: upgrade
      vars:
        upgrade_webapp_image: quay.io/integreatly/tutorial-web-app:{{ webapp_version }}
        upgrade_webapp_operator_image: quay.io/integreatly/tutorial-web-app-operator:{{ webapp_operator_release_tag }}

    - include_role:
        name: backup
        tasks_from: upgrade
      vars:
        upgrade_backup_container_image: quay.io/integreatly/backup-container:{{ backup_version }}

    - include_role:
        name: rhsso
        tasks_from: check_readiness
      vars:
        rhsso_namespace: "{{ eval_rhsso_namespace }}"
        sso_operator_tag: "{{ rhsso_operator_release_tag }}"

    - include_role:
        name: msbroker
        tasks_from: check_readiness
      vars:
        msb_image_tag: "{{ msbroker_release_tag }}"

    - include_role:
        name: webapp
        tasks_from: check_readiness
      vars:
        webapp_operator_tag: "{{ webapp_operator_release_tag }}"
        webapp_image_tag: "{{ webapp_version }}"

    - include_role:
        name: 3scale
        tasks_from: upgrade

    - include_role:
        name: 3scale
        tasks_from: check_readiness

    # Launcher
    - include_role:
        name: launcher
        tasks_from: upgrade

    - include_role:
        name: launcher
        tasks_from: check_readiness

    - name: Update image streams
      include_role:
        name: images
        tasks_from: import
      with_items:
        - 3scale
        - apicurito
        - codeready
        - enmasse
        - fuse
        - launcher
        - sso
        - webapp
      loop_control:
        loop_var: images_source_namespace

    # Fuse
    - include_role:
        name: fuse
        tasks_from: upgrade
      vars:
        old_fuse_tag: "application-templates-2.1.fuse-720018-redhat-00001" # Fuse 7.2 version for deleting old templates
    
    - include_role:
        name: fuse_managed
        tasks_from: upgrade

    - include_role:
        name: fuse_managed
        tasks_from: check_readiness

    # AMQ Online / enmasse
    - include_role:
        name: enmasse
        tasks_from: upgrade

    - include_role:
        name: enmasse
        tasks_from: check_readiness

#Update product version (should always be last)
- import_playbook: "../generate-customisation-inventory.yml"
