---
- hosts: master
  gather_facts: no
  tasks:
    - include_role:
        name: openshift
        tasks_from: set_master_vars
      when: run_master_tasks | default(true) | bool

- hosts: localhost
  gather_facts: yes
  tasks:
    - include_role:
        name: prerequisites
        tasks_from: upgrade
      vars:
        from_versions:
          - "release-1.4.1"
    - set_fact:
        upgrade_webapp_image: quay.io/integreatly/tutorial-web-app:{{ webapp_version }}
        upgrade_webapp_operator_image: quay.io/integreatly/tutorial-web-app-operator:{{ webapp_operator_release_tag }}

    # Managed Service Broker
    - name: Expose vars
      include_vars: "../../roles/rhsso/defaults/main.yml"
    -
      name: Set eval_app_host var
      set_fact:
        eval_app_host: "{{ hostvars['EVAL_VARS']['eval_app_host'] }}"
    - include_role:
        name: msbroker
        tasks_from: upgrade
      vars:
        route_suffix: "{{ eval_app_host }}"
        sso_realm: "{{ rhsso_realm }}"

    # Solution Explorer
    - name: Bump the Web App operator version to {{ webapp_operator_release_tag }}
      shell: oc patch deployment tutorial-web-app-operator -n {{ eval_webapp_namespace }} --type json -p '[{"op":"replace", "path":"/spec/template/spec/containers/0/image", "value":"{{ upgrade_webapp_operator_image }}"}]'
      register: upgrade_webapp_operator
      failed_when: upgrade_webapp_operator.stderr != '' and 'not patched' not in upgrade_webapp_operator.stderr

    - name: Bump the Web App deployment version to {{ webapp_version }}
      shell: oc patch dc tutorial-web-app -n {{ eval_webapp_namespace }} --type json -p '[{"op":"replace", "path":"/spec/template/spec/containers/0/image", "value":"{{ upgrade_webapp_image }}"}]'
      register: upgrade_webapp
      failed_when: upgrade_webapp.stderr != '' and 'not patched' not in upgrade_webapp.stderr

    - name: delete alerts
      shell: "oc delete prometheusrules application-monitoring -n {{ eval_rhsso_namespace }}"

    - name: recreate alerts
      shell: "oc patch keycloak rhsso --type=json --patch='[{\"op\": \"add\", \"path\": \"/status/monitoringResourcesCreated\", \"value\": false}]' -n {{ eval_rhsso_namespace }}"
